// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import (
	httprouter "github.com/julienschmidt/httprouter"
	mock "github.com/stretchr/testify/mock"
)

// IRouterFactory is an autogenerated mock type for the IRouterFactory type
type IRouterFactory struct {
	mock.Mock
}

// CreateRouter provides a mock function with given fields:
func (_m *IRouterFactory) CreateRouter() *httprouter.Router {
	ret := _m.Called()

	var r0 *httprouter.Router
	if rf, ok := ret.Get(0).(func() *httprouter.Router); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*httprouter.Router)
		}
	}

	return r0
}
