// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import (
	database "authserver/database"

	mock "github.com/stretchr/testify/mock"
)

// TransactionFactory is an autogenerated mock type for the TransactionFactory type
type TransactionFactory struct {
	mock.Mock
}

// CreateTransaction provides a mock function with given fields:
func (_m *TransactionFactory) CreateTransaction() (database.Transaction, error) {
	ret := _m.Called()

	var r0 database.Transaction
	if rf, ok := ret.Get(0).(func() database.Transaction); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
