// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import (
	http "net/http"

	httprouter "github.com/julienschmidt/httprouter"
	mock "github.com/stretchr/testify/mock"
)

// RequestHandler is an autogenerated mock type for the RequestHandler type
type RequestHandler struct {
	mock.Mock
}

// DeleteAPIUser provides a mock function with given fields: _a0, _a1, _a2
func (_m *RequestHandler) DeleteAPIUser(_a0 http.ResponseWriter, _a1 *http.Request, _a2 httprouter.Params) {
	_m.Called(_a0, _a1, _a2)
}

// PatchAPIUserPassword provides a mock function with given fields: _a0, _a1, _a2
func (_m *RequestHandler) PatchAPIUserPassword(_a0 http.ResponseWriter, _a1 *http.Request, _a2 httprouter.Params) {
	_m.Called(_a0, _a1, _a2)
}

// PostOAuthToken provides a mock function with given fields: _a0, _a1, _a2
func (_m *RequestHandler) PostOAuthToken(_a0 http.ResponseWriter, _a1 *http.Request, _a2 httprouter.Params) {
	_m.Called(_a0, _a1, _a2)
}

// PostAPIUser provides a mock function with given fields: _a0, _a1, _a2
func (_m *RequestHandler) PostAPIUser(_a0 http.ResponseWriter, _a1 *http.Request, _a2 httprouter.Params) {
	_m.Called(_a0, _a1, _a2)
}
