// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import (
	models "authserver/models"

	mock "github.com/stretchr/testify/mock"
)

// AccessTokenCRUD is an autogenerated mock type for the AccessTokenCRUD type
type AccessTokenCRUD struct {
	mock.Mock
}

// SaveAccessToken provides a mock function with given fields: token
func (_m *AccessTokenCRUD) SaveAccessToken(token *models.AccessToken) error {
	ret := _m.Called(token)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.AccessToken) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
