// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import (
	models "authserver/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AccessTokenCRUD is an autogenerated mock type for the AccessTokenCRUD type
type AccessTokenCRUD struct {
	mock.Mock
}

// DeleteAccessToken provides a mock function with given fields: token
func (_m *AccessTokenCRUD) DeleteAccessToken(token *models.AccessToken) error {
	ret := _m.Called(token)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.AccessToken) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAccessTokenByID provides a mock function with given fields: ID
func (_m *AccessTokenCRUD) GetAccessTokenByID(ID uuid.UUID) (*models.AccessToken, error) {
	ret := _m.Called(ID)

	var r0 *models.AccessToken
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.AccessToken); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AccessToken)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveAccessToken provides a mock function with given fields: token
func (_m *AccessTokenCRUD) SaveAccessToken(token *models.AccessToken) error {
	ret := _m.Called(token)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.AccessToken) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
