// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import (
	models "authserver/models"

	mock "github.com/stretchr/testify/mock"
)

// ScopeCRUD is an autogenerated mock type for the ScopeCRUD type
type ScopeCRUD struct {
	mock.Mock
}

// GetScopeByName provides a mock function with given fields: name
func (_m *ScopeCRUD) GetScopeByName(name string) (*models.Scope, error) {
	ret := _m.Called(name)

	var r0 *models.Scope
	if rf, ok := ret.Get(0).(func(string) *models.Scope); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Scope)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
